apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: wvimuxxd7-go 
  janus-idp.io/tekton: wvimuxxd7-go
  backstage.io/kubernetes-id: wvimuxxd7-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: wvimuxxd7-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml